### ISSUE TITLE
Kinect not found

### ISSUE THREAD

**Issue by vertstream** [secretlocation/azure-kinect-unreal#12] opened 2020-09-24 01:23 UTC
Hey there, I am having trouble getting anything when I hit play. I have added all of the dlls and add the environment variables path and after installing visual studio got the project built and open in unreal. However when I run I get a lot of this in the unreal log:

AzureKinectLog: Error: Kinect device (id : 0) was not found
AzureKinectLog: Error: Kinect device (id : 0) was not found
AzureKinectLog: Warning: Returning empty TArray of UAzureKinectBody

then this
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogWorld: BeginTearingDown for /Game/Maps/UEDPIE_0_Sample
LogSlate: Window 'AzureKinect Preview [NetMode: Standalone] (64-bit/Windows) ' being destroyed
AzureKinectLog: Error: Kinect device (id : 0) was not initialized to be shutdown
AzureKinectLog: Error: Kinect device (id : 0) was not initialized to be shutdown
LogWorld: UWorld::CleanupWorld for Sample, bSessionEnded=true, bCleanupResources=true
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogPlayLevel: Display: Shutting down PIE online subsystems
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogAISub: UAISubsystem::~UAISubsystem AIPerceptionSystem (000002005A461580), frame # 1776
LogAISub: UAISubsystem::~UAISubsystem EnvQueryManager (000002005C731600), frame # 1776
LogUObjectHash: Compacting FUObjectHashTables data took   0.64ms
LogPlayLevel: Display: Destroying online subsystem :Context_1

I can run the kinect body tracking sdk fine but in unreal no front lights on the kinect come one and as it says its not found... I did look for the k4a.log but I cant find one generated.  Any help would be much appreciated.

**Comment by datee** [comment] 2020-11-12 12:17
Hi - i am facing the same issue - anyone have a solution?

**Comment by tejaswingm** [comment] 2020-11-12 17:52
@vertstream and @datee 

Could you kindly check if your environment variables look similar to this? [Reference from Microsoft](https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#collecting-logs)

![azure-kinect-env-variables](https://user-images.githubusercontent.com/8665373/98976024-d3d49580-24e4-11eb-949f-a45c871b4d06.png)

The `k4a.log` will be made in the same folder as the `UE4Editor.exe` (example folder: `C:\Program Files\Epic Games\UE_4.25\Engine\Binaries\Win64`).

If you could attach that k4a.log from there and also the Unreal log from the start when you press Play in Editor, we can take a look and see what the issue is.

Thank you.

**Comment by dylandevs** [comment] 2020-11-16 22:11
Hey guys, sorry about accidentally closing this.

I may have experienced the issue and resolved it in #13 .
The issue I found was from a mismatch with the Azure Kinect plugin installed at 1.4.1, the latest, and the one in the project being 1.4.0. It caused an error where it was looking for `onnxruntime.dll` in the wrong place, so I've committed that to the project now. 

I also rephrased some of the readme for clarity around where the dlls are and how they're referenced. Let me know if this fixes your issue!

**Comment by vertstream** [comment] 2020-11-16 22:48
Thanks Dylan. I did manage to get it running eventually I think the issue actually was I did need to add dnn_model_2.0.onnx which you mentioned wasn’t required but after of i did it started. It worked in 4.24 and 4.25 then. Sorry my unreal knowledge is still developing but can I ask why is the mannequin bound to the centre of the skeleton data in the demo and the skeleton so large? I have test Brekel and ipi and got both working and capturing in sequencer but both have there own quirks. Brekel with a Skelton both retarget to different models okay but my efforts with this just ended with a floating character just the same as the one in the centre of the skeleton like shown here. https://youtu.be/XCS4A7Nl49Q Any data on the retargeting process would be appreciated. Thanks for all your hard work on this.

**Comment by datee** [comment] 2020-11-17 08:46
> @vertstream and @datee
> 
> Could you kindly check if your environment variables look similar to this? [Reference from Microsoft](https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#collecting-logs)
> 
> ![azure-kinect-env-variables](https://user-images.githubusercontent.com/8665373/98976024-d3d49580-24e4-11eb-949f-a45c871b4d06.png)
> 
> The `k4a.log` will be made in the same folder as the `UE4Editor.exe` (example folder: `C:\Program Files\Epic Games\UE_4.25\Engine\Binaries\Win64`).
> 
> If you could attach that k4a.log from there and also the Unreal log from the start when you press Play in Editor, we can take a look and see what the issue is.
> 
> Thank you.

My issue was the same as described above with the missing **`onnxruntime.dll`**
Also there is this problem: (but that seems to be a CUDA issue) 
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1125

Thanks.

**Comment by Cobass** [comment] 2020-12-29 18:18
Hello, having the same issue. What can i do about it?

**Closed** 2021-01-04 17:25 UTC

**Comment by datee** [comment] 2021-01-18 12:30
A note to people having an issue getting this plugin to work on RTX 30xx cards - This is for now not supported by Microsoft / Nvidia it seems. But it is possible to choose what GPU will be used by the Kinect SDK - So i have added this option and made a pull request - here : https://github.com/secretlocation/azure-kinect-unreal/pulls
