### ISSUE TITLE
Trying to build this for 4.24

### ISSUE THREAD

**Issue by lagauche** [secretlocation/azure-kinect-unreal#3] opened 2020-02-06 05:25 UTC
Trying to get this working on 4.24

I think I'm over my head haha. Looks like you took the most complex approach possible with your hybrid c++ and blueprints and your use of a UE4 plugin : )

I'm getting crashes as soon as i hit play. access errors of course. If I disconnect all Event Graph BP except InitAzureKinect, I don't crash but log says:

```
AzureKinectDeviceLog: Error: Kinect device (id : 0) - Initialization Failed with error : Failed to open device!
AzureKinectLog: Error: Kinect device (id : 0) initialization Failed, so cleaning up.
```

Any plans to update this? Happy to help if i can.

**Comment by dylandevs** [comment] 2020-02-11 17:32
Hi @lagauche, we're gonna take a look at this today. We've been upgrading all of our plugins to 4.24, so we'll just do this one next! :)

**Comment by lagauche** [comment] 2020-02-11 20:14
Hey Dylan, awesome, let me know if I can help in any way. Personally if starting from scratch I wouldn't rely on blueprints to the extent you do, but obviously I respect your decision : ) I need to take a closer look at your system, but at first glance it seemed like you could do more if not everything in c++ and just expose the values to blueprints so you can feed that data into the joint/bone modifier in the Anim Graph.

Let me know if I can help in any way. I don't have much of a presence on github, but I am 100% focused on Azure and UE4 right now for my own personal use.

Any idea if it may be possible to package the project on win64 with your implementation?

I wish I knew how to make plugins for ue4 the way you did : ) Maybe it's easier than I think.

I also found a simple integration of the AzureKinect into UE4 here. This person doesn't even need to put any files in the engine / binaries / win64 folder. Maybe that's due to Azure SDK improvements? Packaging isn't working though.

https://github.com/Cris21395/AzureKinectDK

**Comment by tejaswingm** [comment] 2020-02-11 20:21
Hi @lagauche,

I just opened the project in UE 4.24.2 and copied the `dnn_model_2_0.onnx` file to the `<unreal_4.24_installation_folder>/Engine/Binaries/Win64/` folder (as mentioned in the Readme) and it works.

Were you able to `Open the device` using the `Azure Kinect Viewer`? 
`Azure Kinect Viewer` is found in the Installation folder of the SDK. Eg : `C:\Program Files\Azure Kinect SDK v1.2.0\tools`. 
If you haven't installed the SDK, I would suggest you to install the SDK and try opening the device using the `Azure Kinect Viewer`.

Its likely that your PC hasn't recognized the Azure Kinect Device correctly. Try plugging the device into a USB 3.0 port.

Let us know what you find.

**Comment by lagauche** [comment] 2020-02-11 20:56
Heya,

Of course I have! I can open the device in the Azure Kinect Viewer, Brekel Body v3 and I can open it using totally different code in UE4 from https://github.com/Cris21395/AzureKinectDK/blob/master/Source/AzureKinectDK/AzureKinectDKGameModeBase.cpp

I am using the Body SDK 1.0 and the Azure SDK 1.30. Maybe the issue is changes with the SDK? Note: you will have to change NAVAL to NAVEL (if I remember correctly) for the enums in your blueprint to compile.

**Comment by tejaswingm** [comment] 2020-02-11 21:22
Well then I think the SDK difference might be the issue.

I will install the Body SDK 1.0 and Azure Device SDK 1.3.0 and check on my side.

> I also found a simple integration of the AzureKinect into UE4 here. This person doesn't even need to put any files in the engine / binaries / win64 folder. Maybe that's due to Azure SDK improvements? Packaging isn't working though.

huh...It could be that they improved the SDK. But for the previous versions, for the Body Tracking to work, `dnn_model_2_0.onnx` had to be put in the same folder as the UE4Editor.exe.

The reason we included the SDK files (the source include files and the libs, dlls) into the Plugin is because the Plugin can be exported/packaged along with their dependent files and can be put into any project.

**Comment by lagauche** [comment] 2020-02-12 00:30
Totally understand that about the plugin, but any idea if the project itself can be packaged on win64?

**Comment by tejaswingm** [comment] 2020-02-13 16:03
@lagauche I fixed the issue in Updating Azure Kinect SDKs PR #5.
I tested in on my PC and cloned fresh on another PC and it works.

Kindly let us know if you have any more issues.

**Comment by lagauche** [comment] 2020-02-13 23:05
Nice work.

I'm not crashing anymore but the Azure won't initialize. No idea why. Microsoft Body Tracker viewer still working great so it's not about my USB connection etc etc

```
[2020.02.13-22.51.13:692][169]AzureKinectDeviceLog: Error: Kinect device (id : 0) - Initialization Failed with error : Failed to create k4abt tracker!
[2020.02.13-22.51.13:692][169]AzureKinectLog: Error: Kinect device (id : 0) initialization Failed, so cleaning up.
[2020.02.13-22.51.13:796][169]AzureKinectDeviceLog: Warning: KinectDevice Camera is Stopped and Closed
[2020.02.13-22.51.13:796][169]LogBlueprintUserMessages: [BP_TestActor_2] Initializing Azure Kinect
[2020.02.13-22.51.13:796][169]AzureKinectLog: Error: Kinect device (id : 0) was not found
[2020.02.13-22.51.13:796][169]AzureKinectLog: Error: Kinect device (id : 0) was not found
[2020.02.13-22.51.13:796][169]AzureKinectLog: Warning: Returning empty TArray of UAzureKinectBody
[2020.02.13-22.51.13:797][169]PIE: Play in editor start time for /Game/Maps/UEDPIE_0_Sample 0.158
[2020.02.13-22.51.13:797][169]LogBlueprintUserMessages: Late PlayInEditor Detection: Level '/Game/Maps/Sample.Sample:PersistentLevel' has LevelScriptBlueprint '/Game/Maps/Sample.Sample:PersistentLevel.Sample' with GeneratedClass '/Game/Maps/Sample.Sample_C' with ClassGeneratedBy '/Game/Maps/Sample.Sample:PersistentLevel.Sample'
[2020.02.13-22.51.13:797][169]AzureKinectLog: Error: Kinect device (id : 0) was not found
[2020.02.13-22.51.13:797][169]AzureKinectLog: Warning: Returning empty TArray of UAzureKinectBody
```

**Comment by tejaswingm** [comment] 2020-02-14 15:07
oh ok, so the issue is `Failure to create the k4abt tracker`.

This can happen for couple of reasons.
1. The Unreal.exe cannot find these dependent dll files even though they are in a folder that is added to Environment `Path` variable. The Azure Kinect viewer and body tracking viewer works since those exe files are in the same folder as their dependent dlls.
```
 - onnxruntime.dll
 - cudnn64_7.dll
 - cudart64_100.dll
 - cublas64_100.dll
```

**Note:** After adding the environment variable, I had the same issue, so I restarted my PC and it worked. Could you try that if you haven't already restarted your PC?

`OR`

2. It cannot find the `dnn_model_2_0.onnx` file, which shouldn't be the case because this file has been put in the `<project>/Plugins/Binaries/Win64` folder.

Could you check the `k4a.log` and `k4abt.log`? These logs will be in `<unreal_installation_folder>/Engine/Binaries/Win64/` if you have enabled the Azure Kinect Logging.

kindly check [here](https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#collecting-logs) to see how to enable the logs. Its just adding 4 new environment variables.
![azure-kinect-enabling-logs](https://user-images.githubusercontent.com/8665373/74542171-05e2a800-4f11-11ea-9afa-34f001678401.png)

**Comment by lagauche** [comment] 2020-02-14 22:05
No luck yet. I did restart and i have both user and system path set to the body sdk tools folder in program files. I will try moving the dnn_model_2_0.onnx back to engine and see what happens. What else could it be? Any chance of a dnn_model_2_0.onnx version mismatch or?

k4abt.log```
[2020-02-14 17:01:50.902] [info] [t=5832] [K4ABT] D:\a\1\s\src\TrackerHost\TrackerHost.cpp (465): VerifyDependencies(). Verifying Dependencies!
[2020-02-14 17:01:50.904] [info] [t=5832] [K4ABT] D:\a\1\s\src\TrackerHost\TrackerHost.cpp (146): Create(). Initializing CUDA and ONNX Runtime... 
[2020-02-14 17:01:51.047] [error] [t=5832] [K4ABT] D:\a\1\s\src\TrackerHost\TrackerHost.cpp (157): Create(). Load model from C:\Users\lagauche\Desktop\azure-kinect-unreal-master\Plugins\AzureKinectUnreal\Binaries\Win64\dnn_model_2_0.onnx failed:Protobuf parsing failed.
[2020-02-14 17:01:51.047] [error] [t=5832] [K4ABT] D:\a\1\s\src\sdk\k4abt.cpp (38): tracker->Create(sensor_calibration, config) returned failure in k4abt_tracker_create()
```
k4a.log:
```
[2020-02-14 17:01:50.631] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (278): ******************** Device Info ********************
[2020-02-14 17:01:50.631] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (279): K4A SDK version:     1.3.0
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (285): Serial Number:       000227300112
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (289): RGB Sensor Version:  1.6.102
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (292): Depth Sensor Version:1.6.75
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (295): Mic Array Version:   1.6.14
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (298): Sensor Config:       6109.7
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (301): Build type:          Release
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (306): Signature type:      MSFT
[2020-02-14 17:01:50.657] [critical] [t=5832] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (312): ****************************************************

```

**Comment by lagauche** [comment] 2020-02-14 22:14
Fixed it. I think your dnn_model_2_0.onnx got corrupted so I replaced it.

**Comment by tejaswingm** [comment] 2020-02-18 14:48
huh...that is weird. That file was copied directly from the `Body sdk/tools` folder.
Probably a version difference or something in the dnn_model_2_0.onnx file or may be the protobuf version.

In any case, since it is working, I will close this issue.

**Closed by tejaswingm** 2020-02-18 14:48 UTC
Labels: bug
